export const renderConfig = {
  canvas: {
    dprRange: [1, 1.75] as [number, number],
  },
  shadows: {
    contactBlur: 2.25,
    contactFar: 3.2,
    contactFrames: Infinity,
    contactOpacity: 0.31,
    contactResolution: 512,
    contactScale: 4.1,
    floorY: 0.018,
    softFocus: 0.18,
    softSamples: 16,
    softSize: 22,
  },
  floorTexture: {
    size: 192,
    seed: 0x3d1ce,
    baseValue: 205,
    variation: 8,
    fiberStrength: 4,
    speckleStrength: 10,
    repeat: 540,
  },
  ivoryTexture: {
    size: 64,
    seed: 0x1c0ffee,
    baseValue: 218,
    variation: 24,
  },
  lighting: {
    toneMappingExposure: 1.03,
    ambientIntensity: 0.34,
    environmentIntensity: 0.46,
    sources: [
      {
        angle: 0.62,
        castShadow: true,
        color: "#fff2d8",
        decay: 1.5,
        distance: 18,
        id: "key-softbox",
        intensity: 3.15,
        kind: "spot",
        offset: [3.2, 7.2, 4.1] as [number, number, number],
        penumbra: 0.72,
        shadow: {
          bias: -0.00012,
          mapSize: 2048,
          near: 0.4,
          normalBias: 0.018,
        },
      },
      {
        castShadow: false,
        color: "#d8e1ff",
        decay: 1.7,
        distance: 12,
        id: "cool-fill",
        intensity: 0.58,
        kind: "point",
        offset: [-4.6, 3.1, -3.8] as [number, number, number],
      },
      {
        castShadow: false,
        color: "#fff0d1",
        decay: 1.8,
        distance: 9,
        id: "rim-glint",
        intensity: 0.34,
        kind: "point",
        offset: [-2.2, 2.6, 3.8] as [number, number, number],
      },
    ],
  },
  palette: {
    background: "#151614",
    fog: "#151614",
    floor: "#232521",
  },
  performance: {
    sampleDurationMs: 5000,
    maxStoredSamples: 20,
    budgets: {
      desktopDpr1FrameMs: 16.7,
      desktopDpr2FrameMs: 24,
      mobileFrameMs: 33,
      jsGzipKb: 1100,
    },
  },
};
