import type { LightSourceConfig } from "./lighting";

export const renderConfig = {
  canvas: {
    dprRange: [1, 1.5] as [number, number],
  },
  diceGeometry: {
    edgeRadius: 0.155,
    pipDepth: 0.052,
    pipOffset: 0.235,
    pipPaintRadius: 0.073,
    pipRadius: 0.105,
    segments: 44,
  },
  shadows: {
    contactBlur: 1,
    contactFar: 1.5,
    contactOpacity: 0.55,
    contactResolution: 256,
    contactScale: 1.8,
    floorY: 0.003,
  },
  floorTexture: {
    size: 256,
    seed: 0x3d1ce,
    baseValue: 205,
    variation: 8,
    fiberStrength: 4,
    speckleStrength: 10,
    repeat: 1024,
  },
  ivoryTexture: {
    size: 128,
    seed: 0x1c0ffee,
    baseValue: 218,
    variation: 24,
  },
  materials: {
    dice: {
      clearcoat: 0.64,
      clearcoatNormalScale: 0.035,
      clearcoatRoughness: 0.22,
      color: "#fffaf2",
      ior: 1.49,
      normalScale: 0.08,
      roughness: 0.5,
      specularIntensity: 0.5,
    },
    floor: {
      normalScale: 0.055,
      roughness: 1,
    },
    pips: {
      clearcoat: 0.12,
      clearcoatRoughness: 0.46,
      color: "#050403",
      roughness: 0.68,
    },
  },
  lighting: {
    toneMappingExposure: 1.15,
    ambientIntensity: 0.22,
    hemisphereIntensity: 0.38,
    hemisphereSkyColor: "#dfe7f4",
    hemisphereGroundColor: "#161711",
    environmentIntensity: 1.15,
    environmentResolution: 256,
    environmentBackground: "#080907",
    lightformers: [
      {
        color: "#fff3dd",
        id: "warm-key-card",
        intensity: 4.5,
        position: [4, 5, 3] as [number, number, number],
        scale: [4.5, 2.5] as [number, number],
        target: [0, 0.2, 0] as [number, number, number],
      },
      {
        color: "#dce6ff",
        id: "cool-fill-card",
        intensity: 1.4,
        position: [-4, 2.4, -3] as [number, number, number],
        scale: [3, 4] as [number, number],
        target: [0, 0.3, 0] as [number, number, number],
      },
      {
        color: "#fffdf5",
        id: "neutral-top-strip",
        intensity: 2.2,
        position: [0, 6, -4] as [number, number, number],
        scale: [2.2, 1] as [number, number],
        target: [0, 0, 0] as [number, number, number],
      },
    ],
    sources: [
      {
        angle: 0.52,
        castShadow: true,
        color: "#fff2d8",
        decay: 2,
        distance: 18,
        id: "key-softbox",
        intensity: 20,
        kind: "spot",
        offset: [3.6, 7, 4.4] as [number, number, number],
        penumbra: 0.84,
        shadow: {
          bias: -0.00012,
          far: 16,
          intensity: 0.9,
          mapSize: 1024,
          near: 0.4,
          normalBias: 0.004,
          radius: 2.4,
        },
      },
    ] satisfies readonly LightSourceConfig[],
  },
  palette: {
    background: "#151614",
    fog: "#151614",
    floor: "#50534b",
  },
  performance: {
    sampleDurationMs: 5000,
    maxStoredSamples: 20,
    budgets: {
      desktopDpr1FrameMs: 16.7,
      desktopDpr2FrameMs: 24,
      mobileFrameMs: 33,
      jsGzipKb: 1100,
    },
  },
};
